name: "TeslaMate to ABRP"
description: "Publishes TeslaMate data to ABRP to provide semi-realtime journey planning"
version: "1.0.5"
slug: "teslamate_abrp"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_host: "core-mosquitto"
  mqtt_user: null
  mqtt_password: null
  abrp_token: null
  car_number: 1
  car_model: null
schema:
  mqtt_host: str
  mqtt_user: "str?"
  mqtt_password: "str?"
  abrp_token: str
  car_number: int
  car_model: "str?"

